apiVersion: k6.io/v1alpha1
kind: K6
metadata:
  name: {{ include "k6-test.fullname" . }}
spec:
  parallelism: {{ .Values.k6.parallelism }}
  # cleanup: post # If contain this tag, whole k8s resources related to k6 test will be removed after test finished.
  script:
    localFile: {{ .Values.k6.testFile }} # 사용자 custom. 어떤 파일을 테스트할지
  arguments: {{ .Values.k6.arguments }} # 공통. 정책 요소. 변경 가능성 적게 있음.
  starter:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
  runner:
    metadata:
      annotations:
        sidecar.istio.io/inject: "false"
    image: {{ .Values.k6.runner.image }} # 자동으로 변경될 부분, 매번 변경됨. image tag : commit id
    env:
      - name: K6_STATSD_ENABLE_TAGS
        value: 'true'
      - name: K6_STATSD_ADDR
        value: datadog:8125
      - name: K6_INFLUXDB_USERNAME
        value: my-user
      - name: K6_INFLUXDB_PASSWORD
        value: my-password
      - name: K6_INFLUXDB_INSECURE
        value: 'false'
      - name: K6_INFLUXDB_PUSH_INTERVAL
        value: '1s'
      - name: K6_INFLUXDB_CONCURRENT_WRITES
        value: '4'
      - name: SERVER_HOST
        value: {{ .Values.k6.target_server_host }} # 사용자 custom. 어떤 대상을 테스트할지 (bifrost? istio gw? inner call?)
