{{- $runner          := .Values.runner -}}
{{- $aws             := .Values.aws -}}

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $runner.serviceAccount }}
  namespace: {{ $runner.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ $aws.role.arn }}
  labels:
  {{- range $val := $runner.lables }}
    - {{ $val }}
  {{- end }}